package fr.derruette.gradlews.service.rt;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rick' at '06/03/16 14:14' with Gradle 2.7
 *
 * @author Rick, @date 06/03/16 14:14
 */
public class OAuthRequestTest {
	@Test
	public void testWrongResponseGetRequestParam() throws Exception {
		// HttpServletRequest request = new Http; //
		// createMock(HttpServletRequest.class);
		// expect(request.getParameter(OAuth.OAUTH_RESPONSE_TYPE)).andStubReturn(OAuth.ContentType.URL_ENCODED);
		// expect(request.getParameter(OAuth.OAUTH_REDIRECT_URI)).andStubReturn("http://www.example.com/red");
		// expect(request.getParameter("param")).andStubReturn("someparam");
		// replay(request);
		// try {
		// new OAuthAuthzRequest(request);
		// fail("Exception expected");
		// } catch (OAuthProblemException e) {
		// Assert.assertEquals(OAuthError.TokenResponse.INVALID_REQUEST,
		// e.getError());
		// }
		// verify(request);
		// reset(request);
		// expect(request.getParameter(OAuth.OAUTH_RESPONSE_TYPE)).andStubReturn(null);
		// expect(request.getParameter("param")).andStubReturn("someparam");
		// expect(request.getParameter(OAuth.OAUTH_REDIRECT_URI)).andStubReturn("http://www.example.com/red");
		// replay(request);
		// try {
		// new OAuthAuthzRequest(request);
		// fail("Exception expected");
		// } catch (OAuthProblemException e) {
		// Assert.assertEquals(OAuthError.TokenResponse.INVALID_REQUEST,
		// e.getError());
		// }
		// verify(request);
	}
}
